### ISSUE TITLE
Faulty SVG logo

### ISSUE THREAD

**Issue by jamierocks** [Libera-Chat/libera-chat.github.io#11]
The logo[1] fails W3C validation[2], and incorrectly renders on Wikipedia[3] :(

[1] https://libera.chat/static/img/libera-color.svg
[2] https://validator.w3.org/check
[3] https://en.wikipedia.org/wiki/File:Libera_Chat_Logo.svg

**Comment by swantzter** [comment]
That is somewhat intentional, the web version is svgo'd heavily to minimise it. 

I've uploaded the original to the wikipedia page you linked, but I'm not too familiar with the File interface, could you update it to correctly mark the logo as being under CC0 1.0 and I am not the author (noone should be listed given CC0)

thanks

**Comment by jamierocks** [comment]
> I've uploaded the original to the wikipedia page you linked, but I'm not too familiar with the File interface, could you update it to correctly mark the logo as being under CC0 1.0 and I am not the author (noone should be listed given CC0)

No problem, I'll sort that - thanks for sorting that!
