### ISSUE TITLE
Also/alternatively list ed25519 certs for CertFP

### ISSUE THREAD

**Issue by michaelortmann** [Libera-Chat/libera-chat.github.io#16]
Maybe you would like to enhance https://github.com/Libera-Chat/libera-chat.github.io/blob/main/content/_guides/certfp.md

to not only document creation of RSA cert:

`openssl req -x509 -new -newkey rsa:4096 -sha256 -days 1096 -nodes -out libera.pem -keyout libera.pem`

but also creation of Ed25519 (https://en.wikipedia.org/wiki/EdDSA#Ed25519) cert as an alternative:

```
openssl genpkey -algorithm ed25519 -out libera.pem
openssl req -x509 -key libera.pem -days 1096 >>libera.pem
```

Tested successfully against liberachat.

**Comment by glguy** [comment]
I happen to use an ed25519 certificate myself, but I don't think for the common user it matters one way or the other. Older versions of the openssl command line tools don't support this.

Because I don't think it matters giving an option to users will just be potentially confusing and give them a choice they don't need. Power users will continue using fancier crypto systems.

**Comment by emersonveenstra** [comment]
Closing based on glguy's comment, we'd like to keep guides as simple as possible
