### ISSUE TITLE
Add a copyright statement and switch to a free license

### ISSUE THREAD

**Issue by nemobis** [Libera-Chat/libera-chat.github.io#36]
Currently the license statement on this repository is invalid: for instance, it doesn't state the authors or year. Please follow the instructions:
https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

The footer on the website states yet another thing, "© Libera Chat 2021" (without mentioning or linking a license), so that would mean that the website is all rights reserved to an entity called "Libera Chat" (presumably the same entity which is in the process of being incorporated per https://github.com/Libera-Chat/libera-chat.github.io/issues/18 ). If so, the entity has the power to relicense the website to something more appropriate.

The [bylaws](https://libera.chat/bylaws) state that:
> The purpose of the organisation is to provide services such as a community platform for free open-source software and peer directed projects on a volunteer basis.

I'm not entirely sure how to interpret that sentence, but it seems to declare a preference towards [free/libre and open source software](https://fsfe.org/freesoftware/freesoftware.html) and [free works](https://freedomdefined.org/Definition). If so, the website should preferably be under a free license. The CC BY-SA 4.0 is appropriate, but CC BY 4.0 is also an option if you prefer to not have copyleft clauses (I see a mention of MIT license).

**Comment by swantzter** [comment]
For the first question the License section in the readme seems fully compliant with the documentation you linked, like in the website example on that page the author isn't specified since its multiple authors at multiple points in time, captured in git history.

There is no copyright reassignment happening, no contributor has signed such a thing, so the footer should perhaps say "Libera Chat contributors"

We basically just had to pick a license in a short time before going live, we went with MIT for the code part and CC BY-NC-SA for the text/documentation, we may revisit this once things have settled down a little, but note that it would require asking all contributors.

**Comment by nemobis** [comment]
Il 23/05/21 17:02, Svante Bengtson ha scritto:
> Closed #36 via ef46adfcdd1563deeb3d135166191cde6e202e71.

Thanks. Please consider using proper HTML microcode markup 
(<https://microformats.org/wiki/rel-license>) as recommended 
<https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license>.

Please let me know if you need more help to make future contributions 
available *also* under cc-by-sa, so that at some point in the future you 
might be able to use a free license aligned with the goals of supporting 
FLOSS.

**Comment by swantzter** [comment]
That's a good point wrt microcode, I'll keep it in mind for when things have calmed down a little.

And yeah we definitely have on the agenda to at least revisit the CC BY-NC-SA licence at a later date as we know it's not strictly free. Thanks again

**Comment by swantzter** [comment]
added rel=license in 4078727a36c94ade46979a034be932ccba76ed8c'

**Comment by legoktm** [comment]
Thank you for considering switching to a non-NC license. <https://freedomdefined.org/Licenses/NC> goes through some of the pitfalls and reasoning about why NC is harmful.

I would suggest it's something you may want to fix sooner rather than later as people making PRs to this repository would then need to be contacted to get their approval to switch to a different license (or their contributions removed).
