### ISSUE TITLE
Migrade the website on FLOSS alternative?

### ISSUE THREAD

**Issue by Kreyren** [Libera-Chat/libera-chat.github.io#7]
Libera currently provides it's website on GitHub (non-free service).

Consider using https://codeberg.org (arguably supperrior FLOSS alternative providing gitea) and it's https://codeberg.page/

![image](https://user-images.githubusercontent.com/11302521/118853535-277ccd00-b8d4-11eb-88ab-cafdb596ac27.png)

**Comment by swantzter** [comment]
This is not the right place to discuss this.

**Comment by Kreyren** [comment]
What is the right place then? O.o

**Comment by eli-schwartz** [comment]
> Consider using https://codeberg.org (arguably supperrior FLOSS alternative providing gitea)

You can argue anything, even that the moon is made of green cheese. Do people agree with you? Which metrics are you using -- how do you define "superior"?

Here is one example set of definitions in which codeberg is distinctively NOT superior: https://forgeperf.org/

**Comment by Kreyren** [comment]
> You can argue anything, even that the moon is made of green cheese. Do people agree with you? Which metrics are you using -- how do you define "superior"? @eli-schwartz

Four freedom complying service provided by libre service provider with a structure to allow public review and public engagement in the project including voting rights.

Other than that i find it to satisfy my needs for development way better than GitHub as i can work on integration of features to make my life easier that are not possible on GitHub for various reasons such as https://github.com/github/feedback/discussions/2843

Also you can self-host and the gitea upstream is working on federation of the instances as they are currently "just" decentralized e.g. git.fsfe.org use in the wild

Other providers i would recommend are:
- https://git.dotya.ml
- https://git.disroot.org
- https://sr.ht

---

> Here is one example set of definitions in which codeberg is distinctively NOT superior: forgeperf.org @eli-schwartz 

Those results seems very subjective to me assuming that it claims that "sourcehut is the most efficient" while giving them only (assumed) 2 POST requests with a size of 32 KiB compared to Codeberg handling 19 requests of 669 KiB to claim that it's less efficient and accesible? That seems very stupid to me...

![image](https://user-images.githubusercontent.com/11302521/119081881-3612d380-b9fd-11eb-9e9b-0706e885c8b4.png)

**Comment by eli-schwartz** [comment]
So here we get to the heart of the matter. You're badgering libera.chat to choose a platform on which to upload their git repos and ticketing system, based on whether the hosting platform is enabling "public review and public engagement", apparently because you want it to e.g. be accessible over Tor.

Because no FOSS communities ever used github before, due to the argument against github being so clearly obvious that everyone knows it per default and the only thing left is to debate which platform to use instead.

...

Actually no, there isn't much if anything to gain by moving from github to a less-capable and slower github clone. The fundamental issues with github aren't due to the closed development model of the website.

> Also you can self-host and the gitea upstream is working on federation

... is not an argument for hosting on codeberg rather than setting up git.libera.chat

> Those results seems very subjective to me assuming that it claims that "sourcehut is the most efficient" while giving them only (assumed) 2 POST requests with a size of 32 KiB compared to Codeberg handling 19 requests of 669 KiB to claim that it's less efficient and accesible? That seems very stupid to me...

Ok? Feel free to submit a bug report to https://github.com/GoogleChrome/lighthouse telling them their entire basic approach to everything is completely "very stupid" because you want to measure ***website performance***, by "efficiency per kb" instead of, well, performance.

The point remains -- github is the second-best website in terms of performant user interaction and not sucking down bandwidth, after the website with an ethos of "clean/barebones simplicity, be responsive on 15 year old devices or CLI lynx and no JS ever".

I'd say this is a pretty good criteria for choosing a software forge for a project that is not run by the GNU/FSF and doesn't believe it's a moral outrage to use a website without source code or whatever.

At least "you should be self-sufficient and self-host" is a generally understandable and sympathetic argument (and all the more power to people who are empowered by gitea to self-host). But as far as I can tell, nowhere here was self-hosting suggested...

It's not clear to me, what purpose this ticket serves other than generally raising awareness of moral outrage against github.

**Comment by joseeantonior** [comment]
As it has been mentioned before, this is not the right place to discuss this. Locking.
